# Generated by Django 2.2.5 on 2019-12-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoFam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jefefam', models.CharField(max_length=1)),
                ('ip', models.GenericIPAddressField(default='192.168.0.1')),
                ('n_fam', models.IntegerField()),
                ('total_inc', models.IntegerField()),
                ('percapita', models.IntegerField()),
            ],
        ),
    ]
